### PR TITLE
Dbp 453 create redis db cluster available for session storage of spsh

### PR DESCRIPTION
**Pull request by sahassou**
# Description

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

### CODE REVIEW

**Comment by simoncolincap** [comment]
Is this PR ready? I couldn't find a DBP-453 namespace on the dev cluster

**Comment by sahassou** [comment]
> Is this PR ready? I couldn't find a DBP-453 namespace on the dev cluster
Please check : https://github.com/dBildungsplattform/dbildungs-iam-server/actions/runs/8735397433/job/23968534133

As I mentioned in this PR, I only added chart dependencies. The task to install the Redis cluster is included in this PR.
https://github.com/dBildungsplattform/infra-dbp/pull/89/files

**Comment by sahassou** [comment]
This branch has encountered several conflicts. Any further implementation related to this ticket will be handled in [insert branch name or reference: https://github.com/dbildungsplattform/dbildungs-iam-server/tree/DBP-453-create-redis-cluster-spsh

**Comment by sahassou** [comment]
This branch has encountered several conflicts. Any further implementation related to this ticket will be handled in [insert branch name or reference
https://github.com/dbildungsplattform/dbildungs-iam-server/tree/DBP-453-create-redis-cluster-spsh

**Pull request closed without merging**
