### PR TITLE
SPSH-1008: add configuration for LeOniE.SH service provider

### PR DESCRIPTION
**Pull request by niklaskoopmann**
# Description

add link to LeOniE to start page

## Links to Tickets or other pull requests

- https://ticketsystem.dbildungscloud.de/browse/SPSH-1008

## Changes

new tile on start page that links to IQSH service LeOniE 

image

## Datasecurity

n/a

## Deployment

n/a

## New Repos, NPM pakages or vendor scripts

n/a

## Approval for review
- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

### CODE REVIEW

**Review by jaggarnaut — APPROVED** [review]

**Review by marode-cap — COMMENTED** [review]
I'd recommend writing a migration to also add this provider to existing deployments.
Staging will probably be redeployed at least once, but we try our best to keep all the data intact. (And it's good to already get in the habit of writing migrations for things like this)
Take `migrations/Migration20240821150800.ts` as an example

**Comment by niklaskoopmann** [comment]
@marode-cap We get into a kind of chicken-and-egg-situation with the IDs here. But when ditching the seeding data, we can make it work with additional manual configuration in the deployments. Has anyone given this a little more thought already?

**Comment by marode-cap** [comment]
@niklaskoopmann I think this might be the first time, so probably not. I'd accept the PR as it is for now, but we should definitely think about this for the future. Maybe @kristoff-kiefer has some input on this

**Comment by niklaskoopmann** [comment]
@marode-cap Yeah, I'll discuss it with @kristoff-kiefer and @pkleybolte again to find a durable solution. Thanks for the hints! :)

**Pull request merged**
